name: Build and Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run postinstall script
      run: npm run postinstall

    - name: Run development server
      run: npm run dev

    - name: Build application for current platform
      run: npm run package

    - name: Build application for all platforms
      run: npm run package:all

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: production-artifacts
        path: release/build/l
